"""adiciona campo tipo ao modelo Produto

Revision ID: 38d524a72009
Revises: fea01a39c569
Create Date: 2025-07-16 22:17:00.832424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d524a72009'
down_revision = 'fea01a39c569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
